In [27]:
import numpy as np
from numpy import linalg as LA

In [28]:
# Tamaño de la matriz
n = 5

# Crear la diagonal principal
DP=2*np.ones(n)
diagonal_principal = np.diag(DP)

# Crear la diagonal superior
DS=-np.ones(n-1)
diagonal_superior = np.diag(DS, k=1)

# Crear la diagonal inferior
DI=-np.ones(n-1)
diagonal_inferior = np.diag(DI, k=-1)

# Sumar las tres diagonales para obtener la matriz tribanda
matriz_tribanda = diagonal_principal + diagonal_superior + diagonal_inferior
print(matriz_tribanda)

b=np.ones(n)

[[ 2. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0.  0. -1.  2.]]


In [29]:
from scipy.linalg import lu
P, L, U = lu(matriz_tribanda)
U

array([[ 2.        , -1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.5       , -1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.33333333, -1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.25      , -1.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.2       ]])

In [25]:
def Thomas(DP, DS, DI, b):
    n = len(DP)
    x = np.zeros(n)


    for i in range(1, n):
        DP[i] = DP[i] - (DI[i-1] / DP[i-1]) * DS[i-1]
        # Ajustamos el vector b
        b[i] = b[i] - (DI[i-1] / DP[i-1]) * b[i-1]

    # Sustitución hacia adelante
    x[0] = b[0] / DP[0]  # Primer elemento
    for i in range(1, n):
        x[i] = (b[i] - DI[i-1] * x[i-1]) / DP[i]

    return x

# Tamaño de la matriz
n = 5

# Diagonal principal
DP = 2 * np.ones(n)

# Diagonal superior
DS = -np.ones(n - 1)

 # Diagonal inferior
DI = -np.ones(n - 1)

 # Vector b
b = np.ones(n)

# Solución usando el algoritmo modificado
resultado = Thomas(DP, DS, DI, b)
print(resultado)


[0.5        1.33333333 2.5        4.         5.83333333]


In [30]:
Thomas(DP,DS,DI,b)

array([0.5       , 1.33333333, 2.5       , 4.        , 5.83333333])

In [31]:
LA.solve(U,b)

array([2.5, 4. , 4.5, 4. , 2.5])